[Lacros]
    location = "Limassol"
    shortname = "Lim"
[Lacros.settings]
    decoupling = -30
    smooth = true
    grid_time = 6
    max_no_nodes = 15
    thres_factor_co = 6.0
    thres_factor_cx = 3.0
    LDR = true
    station_altitude = 12


[Lacros_at_ACCEPT]
    location = "Cabauw"
    shortname = "Cab"
[Lacros_at_ACCEPT.settings]
    decoupling = -30
    smooth = true
    grid_time = 4
    max_no_nodes = 15
    thres_factor_co = 1.3
    thres_factor_cx = 1.3
    LDR = true
    station_altitude = 12

[Lacros_Pun]
    location = "Punta Arenas"
    shortname = "Pun"
[Lacros_Pun.settings]
    decoupling = -30
    grid_time = 6
    max_no_nodes = 15
    LDR = true
    #roll_velocity = 65 # for 512 bins = 7.92 m/s
    roll_velocity = 98 # = 6.56 m/s
    station_altitude = 9
[Lacros_Pun.settings.peak_finding_params]
    vel_smooth = true
    thres_factor_co = 6.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0


[Polarstern]
    location = "Polarstern"
    shortname = "Pol"
[Polarstern.settings]
    decoupling = -27
    smooth = true
    grid_time = 10
    max_no_nodes = 15
    thres_factor_co = 3.0
    thres_factor_cx = 3.0
    LDR = true
    station_altitude = 12

[Lindenberg]
    location = "Lindenberg"
    shortname = "Lin"
[Lindenberg.settings]
    decoupling = -25
    smooth = true
    grid_time = false
    max_no_nodes = 15
    thres_factor_co = 3.0
    thres_factor_cx = 3.0
    LDR = true
    station_altitude = 100

[Davos]
    location = "Davos"
    shortname = "Dav"
[Davos.settings]
    decoupling = -25
    grid_time = false
    max_no_nodes = 15
    LDR = true
    station_altitude = 1627
[Davos.settings.peak_finding_params]
    vel_smooth = true
    thres_factor_co = 6.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0

[kazr_baecc] 
    location = "Hyytiala" 
    shortname = "kazrbaecc" 
[kazr_baecc.settings] 
    smooth = true 
    grid_time = 6 
    max_no_nodes = 15 
    thres_factor_co = 3.0 
    #thres_factor_cx = 3.0 
    LDR = false 
    station_altitude = 181

[kazr_mosaic] 
    location = "MOSAiC" 
    shortname = "kazrmosaic" 
[kazr_mosaic.settings] 
    grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[kazr_mosaic.settings.peak_finding_params]
    vel_smooth = true
    thres_factor_co = 3.0 
    thres_factor_cx = 3.0

[joyrad_nya] 
    location = "Ny-Alesund" 
    shortname = "joyrad_nya" 
[joyrad_nya.settings] 
    #smooth = true 
    smooth = 'broad' 
    grid_time = 4 
    max_no_nodes = 15 
    # for joyrad test linear factor
    thres_factor_co = 2 
    #thres_factor_cx = 3.0 
    LDR = false 
    station_altitude = 10
